#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Author: Chunyu Xue

"""
A script related to the global resource interface serving for the scheduler 
with runtime job workload.
"""

from resources.resource_abs import GPUStatus


class ResourceInterface:
    """ 
    The class of resource interface, which provides APIs for global scheduler to runtime 
    interact with cluster resources and dispatch job workload. 
    """
    def __init__(self, node_pool: dict):
        self.node_pool = node_pool
    
    def get_gtype_num_table(self, only_idle_gpus: bool = False):
        """ Get the mapping from gpu type to gpu num. """
        _table = dict()
        for _nid in self.node_pool:
            node = self.node_pool[_nid]
            if node.gpu_type not in _table:
                _table[node.gpu_type] = node.capacity if not only_idle_gpus else node.idle_gpu_num
            else:
                _table[node.gpu_type] += node.capacity if not only_idle_gpus else node.idle_gpu_num
        return _table
    
    def get_crs_table(self):
        """ 
        Get the table of Cluster Resources Status (CRS). 
        -------------------------------------------------
        Return:
            - crs_table: { 'node_id': Node.gpu_status, ...}
        """
        # TODO(chunyu): Add unmodified flag of nodes and store/load cache instead of regenerate.
        _table = dict()
        for _nid in self.node_pool:
            _table[_nid] = self.node_pool[_nid].gpu_status
        return _table

    def apply_sched(self, crs_table: dict):
        """ 
        Apply scheduling decision (in crs_table format) generated by the global scheduler 
        on real cluster resources. 
        """
        for _nid in crs_table:
            node = self.node_pool[_nid]
            for _gid in crs_table[_nid]:
                gpu = node.get_gpu_by_uuid(_gid)
                # Current gpu status
                _gpu_stat = crs_table[_nid][_gid]
                (cur_type, cur_status, cur_used_jid) = (_gpu_stat["type"], _gpu_stat["status"], 
                                                        _gpu_stat["used_job_id"])
                assert gpu.type == cur_type, \
                    f"Mismatched gpu type when attempting to update gpu status: {gpu.type}, {cur_type}"
                if gpu.status != cur_status:
                    # Update status
                    gpu.update_status(GPUStatus(cur_status))
                if node.gpu_to_job_table[_gid]["used"] != cur_used_jid:
                    # Update occupied job id
                    node.gpu_to_job_table[_gid]["used"] = cur_used_jid
